/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AiAudioResult = {
    'ok' : { 'audioBase64' : string, 'metadata' : string, 'mimeType' : string }
  } |
  { 'err' : string };
export type AiDesignResult = { 'ok' : { 'suggestions' : string } } |
  { 'err' : string };
export type AiImageResult = {
    'ok' : { 'mimeType' : string, 'imageBase64' : string }
  } |
  { 'err' : string };
export interface Project {
  'title' : string,
  'content' : string,
  'projectType' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'createProject' : ActorMethod<[string, string, string], bigint>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  /**
   * / Poll a Replicate prediction by ID to check if it has completed.
   * / Returns the raw JSON response from Replicate (status, output, error fields).
   */
  'getAiPredictionStatus' : ActorMethod<[string], AiDesignResult>,
  'getProject' : ActorMethod<[bigint], Project>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  /**
   * / Process base64-encoded audio using an AI operation.
   * / operation: "vocals_separate" | "enhance_voice" | "normalize"
   * / Returns processed audio as base64 or a mock if no API key is set.
   */
  'processAiAudio' : ActorMethod<[string, string], AiAudioResult>,
  /**
   * / Get AI-powered design suggestions: font matches, color palettes, text suggestions.
   * / Returns JSON string with suggestions array.
   */
  'processAiDesign' : ActorMethod<[string, string, string], AiDesignResult>,
  /**
   * / Process a base64-encoded image using an AI operation.
   * / operation: "colorize" | "cartoon" | "portrait_blur" | "object_remove" | "age_filter"
   * / Returns the processed image as base64 or a mock if no API key is set.
   */
  'processAiImage' : ActorMethod<[string, string], AiImageResult>,
  'setAiApiKey' : ActorMethod<[string], undefined>,
  'updateProject' : ActorMethod<
    [bigint, [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];