/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AiDesignResult = IDL.Variant({
  'ok' : IDL.Record({ 'suggestions' : IDL.Text }),
  'err' : IDL.Text,
});
export const Time = IDL.Int;
export const Project = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'projectType' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
});
export const AiAudioResult = IDL.Variant({
  'ok' : IDL.Record({
    'audioBase64' : IDL.Text,
    'metadata' : IDL.Text,
    'mimeType' : IDL.Text,
  }),
  'err' : IDL.Text,
});
export const AiImageResult = IDL.Variant({
  'ok' : IDL.Record({ 'mimeType' : IDL.Text, 'imageBase64' : IDL.Text }),
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'getAiPredictionStatus' : IDL.Func([IDL.Text], [AiDesignResult], []),
  'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'processAiAudio' : IDL.Func([IDL.Text, IDL.Text], [AiAudioResult], []),
  'processAiDesign' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [AiDesignResult],
      [],
    ),
  'processAiImage' : IDL.Func([IDL.Text, IDL.Text], [AiImageResult], []),
  'setAiApiKey' : IDL.Func([IDL.Text], [], []),
  'updateProject' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AiDesignResult = IDL.Variant({
    'ok' : IDL.Record({ 'suggestions' : IDL.Text }),
    'err' : IDL.Text,
  });
  const Time = IDL.Int;
  const Project = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'projectType' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  const AiAudioResult = IDL.Variant({
    'ok' : IDL.Record({
      'audioBase64' : IDL.Text,
      'metadata' : IDL.Text,
      'mimeType' : IDL.Text,
    }),
    'err' : IDL.Text,
  });
  const AiImageResult = IDL.Variant({
    'ok' : IDL.Record({ 'mimeType' : IDL.Text, 'imageBase64' : IDL.Text }),
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'getAiPredictionStatus' : IDL.Func([IDL.Text], [AiDesignResult], []),
    'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'processAiAudio' : IDL.Func([IDL.Text, IDL.Text], [AiAudioResult], []),
    'processAiDesign' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [AiDesignResult],
        [],
      ),
    'processAiImage' : IDL.Func([IDL.Text, IDL.Text], [AiImageResult], []),
    'setAiApiKey' : IDL.Func([IDL.Text], [], []),
    'updateProject' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };