/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type AiAudioResult = {
    __kind__: "ok";
    ok: {
        audioBase64: string;
        metadata: string;
        mimeType: string;
    };
} | {
    __kind__: "err";
    err: string;
};
export type Time = bigint;
export interface Project {
    title: string;
    content: string;
    projectType: string;
    owner: Principal;
    createdAt: Time;
    updatedAt: Time;
}
export type AiImageResult = {
    __kind__: "ok";
    ok: {
        mimeType: string;
        imageBase64: string;
    };
} | {
    __kind__: "err";
    err: string;
};
export type AiDesignResult = {
    __kind__: "ok";
    ok: {
        suggestions: string;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface backendInterface {
    createProject(title: string, projectType: string, content: string): Promise<bigint>;
    deleteProject(id: bigint): Promise<void>;
    /**
     * / Poll a Replicate prediction by ID to check if it has completed.
     * / Returns the raw JSON response from Replicate (status, output, error fields).
     */
    getAiPredictionStatus(predictionId: string): Promise<AiDesignResult>;
    getProject(id: bigint): Promise<Project>;
    getProjects(): Promise<Array<Project>>;
    /**
     * / Process base64-encoded audio using an AI operation.
     * / operation: "vocals_separate" | "enhance_voice" | "normalize"
     * / Returns processed audio as base64 or a mock if no API key is set.
     */
    processAiAudio(audioBase64: string, operation: string): Promise<AiAudioResult>;
    /**
     * / Get AI-powered design suggestions: font matches, color palettes, text suggestions.
     * / Returns JSON string with suggestions array.
     */
    processAiDesign(prompt: string, designType: string, brandColors: string): Promise<AiDesignResult>;
    /**
     * / Process a base64-encoded image using an AI operation.
     * / operation: "colorize" | "cartoon" | "portrait_blur" | "object_remove" | "age_filter"
     * / Returns the processed image as base64 or a mock if no API key is set.
     */
    processAiImage(imageBase64: string, operation: string): Promise<AiImageResult>;
    setAiApiKey(key: string): Promise<void>;
    updateProject(id: bigint, title: string | null, content: string | null): Promise<void>;
}
import type { AiAudioResult as _AiAudioResult, AiDesignResult as _AiDesignResult, AiImageResult as _AiImageResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createProject(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getAiPredictionStatus(arg0: string): Promise<AiDesignResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getAiPredictionStatus(arg0);
                return from_candid_AiDesignResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAiPredictionStatus(arg0);
            return from_candid_AiDesignResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return result;
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return result;
        }
    }
    async processAiAudio(arg0: string, arg1: string): Promise<AiAudioResult> {
        if (this.processError) {
            try {
                const result = await this.actor.processAiAudio(arg0, arg1);
                return from_candid_AiAudioResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processAiAudio(arg0, arg1);
            return from_candid_AiAudioResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async processAiDesign(arg0: string, arg1: string, arg2: string): Promise<AiDesignResult> {
        if (this.processError) {
            try {
                const result = await this.actor.processAiDesign(arg0, arg1, arg2);
                return from_candid_AiDesignResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processAiDesign(arg0, arg1, arg2);
            return from_candid_AiDesignResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async processAiImage(arg0: string, arg1: string): Promise<AiImageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.processAiImage(arg0, arg1);
                return from_candid_AiImageResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processAiImage(arg0, arg1);
            return from_candid_AiImageResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAiApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAiApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAiApiKey(arg0);
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: string | null, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_AiAudioResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AiAudioResult): AiAudioResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_AiDesignResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AiDesignResult): AiDesignResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_AiImageResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AiImageResult): AiImageResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        suggestions: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        suggestions: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        audioBase64: string;
        metadata: string;
        mimeType: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        audioBase64: string;
        metadata: string;
        mimeType: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        mimeType: string;
        imageBase64: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        mimeType: string;
        imageBase64: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
